//
//  Constants.swift
//  E-detailer
//
//  Created by Ammad on 8/3/18.
//  Copyright © 2018 Ammad. All rights reserved.

import Foundation

class Constants {
//        static let BaseUrl = "http://192.168.100.101/"
    static let BaseUrl = "http://novo.digitrends.pk/"
    
//        static let BaseUrl = "http://novobeta.digitrends.pk/"
    
    static let DcrBaseUrl = "http://novo-dcr.digitrends.pk/"
//    static let DcrBaseUrl = "http://novo-dcrbeta.digitrends.pk/"
    
//    static let LoginApi = BaseUrl + "Account/Login"
    static let LoginApi2 = BaseUrl + "api/LoginJwtApi/Login"
    static let CityApi = BaseUrl + "webapi/GetAllBaseStationRoute"
    static let AttendencePostApi = BaseUrl + "/webapi/AddListCPAttendanceOfflineVersion10"
    static let FileUploadApi = BaseUrl + "/webapi/FileUploaderWithUrl"
    static let ContentApi = BaseUrl + "Account/getcontent"
    static let TripleVisitApi = BaseUrl + "DEUWebApi/TripleVisitEvaluationFormSubmit"
    static let DualVisitApi = BaseUrl + "DEUWebApi/DualVisitEvaluationFormSubmit"
    static let SyncHomeActivity = BaseUrl + "DEUWebApi/PostCallSync"
    static let AllPatientsApi = BaseUrl + "DEUWebApi/GetPatients?employeeId=%@"
    static let PlannedPatientsApi = BaseUrl + "DEUWebApi/GetPatientsPlan?employeeId=%@&Date=%@"
    static let PostSamAndExpenseApi = BaseUrl + "ExpensesSync/PostExpensesManager"
    static let MSLActivityApi = BaseUrl + "MslActivity/PostMslActivity"
    static let PatientReschuledApi = BaseUrl + "DEUWebApi/ReschedulePlan"
    static let PatientProductApi = BaseUrl + "DEUWebApi/EducationalActivityProduct"
    static let CreatePatientApi = BaseUrl + "DEUWebApi/CreatePatient"
    static let PatientCancelApi = BaseUrl + "DEUWebApi/CancelPlan"
    static let CallApi = BaseUrl + "api/callsyncv1"
    static let CallDualApi = BaseUrl + "DEUWebApi/DualVisitEvaluationFormSubmit"
    static let CallTripleApi = BaseUrl + "DEUWebApi/TripleVisitEvaluationFormSubmit"
    static let ContactApi = BaseUrl + "webapi/GetAllContactPoints"
    static let DoctorApi = BaseUrl + "Account/EmployeeDoctors"
    static let getAllPlannedDoc = BaseUrl + "WebApi/GetMSRPlanV1"
    static let GetPatientDataApi = BaseUrl + "DEUWebApi/EducationalActivityFormList"
    static let ManagerApi = BaseUrl + "Account/EmployeeManagerDetails"
    static let SampleAndExpenseApi = BaseUrl + "Account/GetSamplesandExpense"
    static let StatisticsApi = DcrBaseUrl + "webapi//padashboard"
    static let CategoryApi = BaseUrl + "pdf/GetAllCategoriesTreeView"
    static let VideoContentApi = BaseUrl + "Account/getvideos"
    static let AttendenceApi = BaseUrl + "Account/GetAttendanceMarkTimeVersion10"
    static let GetPlannedPatientApi = BaseUrl + "DEUWebApi/GetPatientsPlan"
    static let GetAllPatientPlan = BaseUrl + "DEUWebApi/GetAllPatientPlans?patientId=%@"
    static let CryptoKeyPassPhrase = "hi;Ar;Pak"
    static let HcpPostData = "HcpPostData"
    static let ATPostData = "ATPostData"
    static let CallPCApi = BaseUrl + "DEUWebApi/PerformanceEvaluationFormPC"
    static let CallDEApi = BaseUrl + "DEUWebApi/PerformanceEvaluationFormDE"
    static let imageUrlApi = "/webapi/FileUploaderWithUrl"
    static let getPlanApi = BaseUrl + "DEUWebApi/GetplannedEmployees"
    static let getUnPlannedApi = BaseUrl + "DEUWebApi/GetUnplannedEmployees"
    static let getCallCount = BaseUrl + "DEUWebApi/GetDiabatiesAwarenessEducationStats?employeeId=%@&date=%@"
    static let getClicnicCallApi = BaseUrl + "DEUWebApi/GetClinicalActivityCalls?employeeId=%@&date=%@"
    static let getPatientactivity = BaseUrl + "DEUWebApi/GetClinicalActivityPatients?employeeId=%@&date=%@"
    static let getHomeCallDetail = BaseUrl + "DEUWebApi/GetHomeActivityCall?employeeId=%@&date=%@"
    static let getHomeActivityVisit = BaseUrl + "DEUWebApi/GetHomeActivityVisit?employeeId=%@&date=%@"
    static let getHomeActivityPatient = BaseUrl + "DEUWebApi/GetHomeActivityNewPatient?employeeId=%@&date=%@"
    static let territoryCode = "territoryCode"
    static let screen1 = "screen1"
    static let startDate = "startDate"
    static let designation = "designation"
    static let zone = "zone"
    static let selectedDoctorId = "selectedDoctorId"
    static let selectedName = "selectedName"
    static let planStatus = "planStatus"
    static let SstartTime = "SstartTime"
    static let OutPostData = "OutPostData"
    static let CcompleteTime = "CcompleteTime"
    static let AddComments = "AddComments"
    static let imgUrl = "imgUrl"
    static let eduStr = "eduStr"
    static let eduEnd = "eduEnd"
    static let EduPostData = "EduPostData"
    static let uploadImage = "uploadImage"
    static let imgURL = "imgURL"
    static let selectedDate = "selectedDate"
    static let currentDate = "currentDate"
    static let patientId = "patientId"
    static let ishardCopy = "ishardCopy"
    static let getCity = "getCity"
    static let isexplained = "isexplained"
    static let ishardselect = "ishardselect"
    static let isexplainedselect = "isexplainedselect"
    static let callselectedDate = "callselectedDate"
    static let dualPostData = "dualPostData"
    static let triplePostData = "triplePostData"
    static let CallToUploadKey = "CallToUploadKey"
    static let TypeProduct = "Product"
    static let TypeVideo = "Video"
    static let TypePdf = "Pdf"
    static let RootDir = "eDetailer"
    static let DownloadDir = "Downloads"
    static let patResult = "patResult"
    static let clinicPostData = "clinicPostData"
    static let LOGIN_RESULT = "login_result"
    static let EMP_ID = "EMP_ID"
    static let LatitudeKey = "Latitude"
    static let LongitudeKey = "Lonitude"
    static let LastTimeOfUpload = "LastTimeOfUpload"
    static let TypeApi = "Api"
    static let IsSignInKey = "IsSignInKey"
    static let MorningStartTime = "MorningStartTime"
    static let MaxMorningTime = "MaxMorningTime"
    static let EveningTimeStart = "EveningTimeStart"
    static let MaxEveningTime = "maxEveningTime"
    static let validate = "validate"
    static let activity = "activity"
    static let Emp_Name = "Emp_Name"
    static let startTime = "startTime"
    static let expDate = "expDate"
    static let expCode = "expCode"
    static let expType = "expType"
    static let expTypeId = "expTypeId"
    static let expAmount = "expAmount"
    static let cityId = "cityId"
    static let getDesId = "getDesId"
    static let expNotes = "expNotes"
    static let expPostData = "expPostData"
    static let expCityName = "expCityName"
    static let desName = "desName"
    static let HCPDate = "HCPDate"
   
}
